changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Alterações significativas 🛠
      labels:
        - Semver-Major
        - breaking-change
    - title: Novas features 🎉
      labels:
        - Semver-Minor
        - enhancement
    - title: Outras mudanças
      labels:
        - "*"