name: Release python on-demand

on: [workflow_dispatch]

jobs:
  build-python:
    runs-on: windows-latest
    timeout-minutes: 10
    permissions:
      contents: write
    defaults:
      run:
        shell: powershell
    steps:
      - name: Checkout da branch
        uses: actions/checkout@v3

      - name: Calcula proxima versão (semver)
        uses: ietf-tools/semver-action@v1
        id: semver
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          patchAll: true
          skipInvalidTags: true

      # Aqui entraria o processo de build com a tag nova
      - name: Adiciona uma tag com a versão nova
        uses: anothrNick/github-tag-action@1.64.0
        id: "tag_create"
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          CUSTOM_TAG: ${{ steps.semver.outputs.nextStrict }}
  
      - name: Gera o changelog
        uses: requarks/changelog-action@v1
        id: changelog
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.semver.outputs.nextStrict }}

      - name: Gera um zip com os artefatos do release
        run: tar.exe acvf python.tar.gz -C .github\workflows releasePython.yml

      - name: Gera o rascunho do release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'python.tar.gz'
          draft: true
          generateReleaseNotes: true
          body: ${{ steps.changelog.outputs.changes }}
          tag: ${{ steps.semver.outputs.nextStrict }}
