name: Release python on-demand

on: [workflow_dispatch]

jobs:
  build-python:
    runs-on: windows-latest
    timeout-minutes: 10
    permissions:
      contents: write
    defaults:
      run:
        shell: powershell
    steps:
      - uses: actions/checkout@v3
      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: desenv
          patchAll: true
          skipInvalidTags: true
          prefix: 'python/'
      - name: Zip
        run: tar.exe acvf python.tar.gz -C .github\workflows releasePython.yml
      - name: release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'python.tar.gz'
          draft: true
          generateReleaseNotes: true
          tag: ${{ steps.semver.outputs.nextStrict }}
          commit: 'desenv'
