name: Release electron on-demand

on: [workflow_dispatch]

jobs:
  build-python:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - name: Checkout da branch
        uses: actions/checkout@v3

      - name: Printa o ls
        run: |
          echo "${{ github.repository }}"
          ls

      - name: Baixa o zip
        run: gh release download 0.2.0 -R ${{ github.repository }}

      # - name: Baixa o zip com o python
      #   uses: robinraju/release-downloader@v1.8
      #   with: 
      #     fileName: "python.tar.gz"
      #     extract: true
      #     tag: "0.1.0"

      - name: Printa o ls denovo
        run: ls
